# Generated by Django 3.2 on 2021-07-18 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopotion', '0002_remove_pet_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='Description',
            new_name='description',
        ),
    ]
